CREATE TABLE CSE532.STOCK(StockName CHAR(4), Date DATE, Open DOUBLE, High DOUBLE, Low DOUBLE, Close DOUBLE, AdjClose DOUBLE, Volume DOUBLE);
CREATE INDEX STOCK_DATE_INDEX ON CSE532.STOCK(Date);
CREATE INDEX CLOSE_INDEX ON CSE532.STOCK(Close);
CREATE INDEX ADJ_CLOSE_INDEX ON CSE532.STOCK(AdjClose);